// <auto-generated />
using System;
using WebAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(ThietLapContext))]
    partial class ThietLapContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FullProject.Model.BangCong", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ThangTinhCong")
                        .HasColumnType("nvarchar(7)");

                    b.HasKey("MaNV", "ThangTinhCong");

                    b.HasIndex("ThangTinhCong");

                    b.ToTable("BangCongs");
                });

            modelBuilder.Entity("FullProject.Model.BangPhatDiMuon", b =>
                {
                    b.Property<string>("ThangTinhCong")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<int>("SoGioTinhMuon")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienPhatMuon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SoTienPhatNghiLam")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ThangTinhCong");

                    b.ToTable("PhatDiMuons");
                });

            modelBuilder.Entity("FullProject.Model.ChamCong", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("NgayChamCong")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("GioRa")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioVao")
                        .HasColumnType("time");

                    b.HasKey("MaNV", "NgayChamCong");

                    b.ToTable("ChamCongs");
                });

            modelBuilder.Entity("FullProject.Model.LichSu", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoatDong")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("NgayGio")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("TenTaiKhoan");

                    b.ToTable("LichSus");
                });

            modelBuilder.Entity("FullProject.Model.Luong", b =>
                {
                    b.Property<string>("MaNV")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ThangLinhLuong")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("LuongCung")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Thue")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaNV", "ThangLinhLuong");

                    b.ToTable("Luongs");
                });

            modelBuilder.Entity("FullProject.Model.NhanVien", b =>
                {
                    b.Property<string>("MaNV")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("BatDauLamViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("CCCD")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime>("ChinhThucLamViec")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChucVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DiaChiTamChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiaChiThuongChu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaBaoHiem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaPhongBan")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MailLamViec")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgayNghiViec")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("STKNganHang")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TenNganHang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrinhDoHocVan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("YeuCauChamCong")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaNV");

                    b.HasIndex("MaPhongBan");

                    b.ToTable("NhanViens");
                });

            modelBuilder.Entity("FullProject.Model.PhongBan", b =>
                {
                    b.Property<string>("MaPhongBan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaPhongBan");

                    b.ToTable("PhongBans");
                });

            modelBuilder.Entity("FullProject.Model.TaiKhoan", b =>
                {
                    b.Property<string>("TenTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TenTaiKhoan");

                    b.HasIndex("MaNV")
                        .IsUnique();

                    b.ToTable("TaiKhoans");
                });

            modelBuilder.Entity("FullProject.Model.ThietLap", b =>
                {
                    b.Property<string>("ThangTinhCong")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<int>("NgayCongBatBuoc")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<int>("NgayPhepToiDa")
                        .HasColumnType("int");

                    b.HasKey("ThangTinhCong");

                    b.ToTable("ThietLaps");
                });

            modelBuilder.Entity("FullProject.Model.ThuongPhat", b =>
                {
                    b.Property<int>("MaThuongPhat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongPhat"));

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaNV")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Ngay")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguonThuongPhat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaThuongPhat");

                    b.HasIndex("MaNV");

                    b.ToTable("ThuongPhats");
                });

            modelBuilder.Entity("FullProject.Model.BangCong", b =>
                {
                    b.HasOne("FullProject.Model.NhanVien", "NhanVien")
                        .WithMany("BangCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullProject.Model.ThietLap", "ThietLap")
                        .WithMany()
                        .HasForeignKey("ThangTinhCong")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");

                    b.Navigation("ThietLap");
                });

            modelBuilder.Entity("FullProject.Model.ChamCong", b =>
                {
                    b.HasOne("FullProject.Model.NhanVien", "NhanVien")
                        .WithMany("ChamCongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FullProject.Model.LichSu", b =>
                {
                    b.HasOne("FullProject.Model.TaiKhoan", "TaiKhoan")
                        .WithMany("LichSus")
                        .HasForeignKey("TenTaiKhoan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("FullProject.Model.Luong", b =>
                {
                    b.HasOne("FullProject.Model.NhanVien", "NhanVien")
                        .WithMany("Luongs")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FullProject.Model.BangPhatDiMuon", "BangPhatDiMuon")
                        .WithMany("Luong")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BangPhatDiMuon");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FullProject.Model.NhanVien", b =>
                {
                    b.HasOne("FullProject.Model.PhongBan", "PhongBan")
                        .WithMany("NhanViens")
                        .HasForeignKey("MaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PhongBan");
                });

            modelBuilder.Entity("FullProject.Model.TaiKhoan", b =>
                {
                    b.HasOne("FullProject.Model.NhanVien", "NhanVien")
                        .WithOne("TaiKhoan")
                        .HasForeignKey("FullProject.Model.TaiKhoan", "MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FullProject.Model.ThuongPhat", b =>
                {
                    b.HasOne("FullProject.Model.NhanVien", "NhanVien")
                        .WithMany("ThuongPhats")
                        .HasForeignKey("MaNV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("FullProject.Model.BangPhatDiMuon", b =>
                {
                    b.Navigation("Luong");
                });

            modelBuilder.Entity("FullProject.Model.NhanVien", b =>
                {
                    b.Navigation("BangCongs");

                    b.Navigation("ChamCongs");

                    b.Navigation("Luongs");

                    b.Navigation("TaiKhoan")
                        .IsRequired();

                    b.Navigation("ThuongPhats");
                });

            modelBuilder.Entity("FullProject.Model.PhongBan", b =>
                {
                    b.Navigation("NhanViens");
                });

            modelBuilder.Entity("FullProject.Model.TaiKhoan", b =>
                {
                    b.Navigation("LichSus");
                });
#pragma warning restore 612, 618
        }
    }
}
